version: "3"

services:
  search:
    image: dcatno/search:latest
    expose:
     - "3000"

  search-api:
    image: dcatno/search-api:latest
    expose:
      - "8080"
    depends_on:
      - elasticsearch

  api-cat:
    image: dcatno/api-cat:latest
    expose:
      - "8080"
      - "8181"
    depends_on:
      - elasticsearch5
      - reference-data

  nginx-search:
    image: dcatno/nginx-search:latest
    expose:
     - "8080"
    depends_on:
      - search
      - search-api
      - harvester-api

  fuseki:
    image: dcatno/fuseki:latest
    expose:
     - "8080"

  harvester-api:
    image: dcatno/harvester-api:latest
    expose:
     - "8080"
    depends_on:
     - fuseki
     - elasticsearch
     - reference-data

  harvester:
    image: dcatno/harvester:latest
    expose:
     - "8080"
    depends_on:
     - elasticsearch
     - fuseki
     - harvester-api

  elasticsearch5:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9

  elasticsearch:
    image: elasticsearch:2.4.1
    expose:
     - "9200"
     - "9300"

  elasticsearch-copy:
    image: dcatno/elasticsearch-copy:latest

  dev-management:
    image: dcatno/dev-management:latest
    expose:
     - "8080"
    depends_on:
      - elasticsearch
      - fuseki
      - harvester-api

  nginx-registration:
    image: dcatno/nginx-registration:latest
    expose:
     - "8080"
    depends_on:
      - registration-react
      - registration-api
      - reference-data

  registration-api:
    image: dcatno/registration-api:latest
    expose:
     - "8080"
    depends_on:
      - elasticsearch
      - reference-data
      - registration-auth

  registration-react:
    image: dcatno/registration-react:latest
    expose:
     - "4300"

  registration-auth:
    image: dcatno/registration-auth:latest
    expose:
     - "8080"

  reference-data:
    image: dcatno/reference-data:latest
    expose:
     - "8080"

  e2e:
    image: dcatno/e2e:latest
    volumes:
      - ./applications/e2e/test:/usr/src/app/test:rw
    command: tail -F /dev/null
