spring.jackson.default-property-inclusion: non_null
logging:
  level.: WARN
  level.no.acat: DEBUG
  level.org.springframework: WARN
  level.org.springframework.web: WARN
application:
  referenceDataUrl: http://reference-data:8080
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES}
  clusterName: ${FDK_ES_CLUSTERNAME}
server:
  port: 8080
management:
  server:
    port: 8181

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
application:
  referenceDataUrl: http://localhost:8100
elastic:
  clusterNodes: localhost:9301
  clusterName: elasticsearch
server:
  port: 8087
management:
  server:
    port: 8997
